package nju.software.jxjs.model;


// Generated 2015-3-2 17:43:59 by Hibernate Tools 3.4.0.CR1

/**
 * TGypz generated by hbm2java
 */
public class TGypz implements java.io.Serializable
{

	private static final long serialVersionUID = 1L;
	private int bh;
	private int pzbh;
	private String lx;
	private String mc;
	
	public TGypz()
	{
	}
	
	public TGypz(String mc)
	{
		this.mc = mc;
	}
	
	public TGypz(int bh, int pzbh, String mc)
	{
		this.bh = bh;
		this.pzbh = pzbh;
		this.mc = mc;
	}

	public TGypz(int bh, int pzbh, String lx, String mc)
	{
		this.bh = bh;
		this.pzbh = pzbh;
		this.lx = lx;
		this.mc = mc;
	}
	
	@Override
	public boolean equals(Object obj)
	{
		if(obj instanceof TGypz)
		{
			TGypz gypz = (TGypz)obj;
			if((this.bh == gypz.getBh()) && (this.pzbh == gypz.getPzbh()) 
					&& (this.lx.equals(gypz.getLx())) && (this.mc.equals(gypz.getMc())))
			{
				return true;
			}
		}
		
		return false;
	}
	
	@Override
	public int hashCode()
	{
		int result = 17;
		result = result * 37 + this.bh;
		result = result * 37 + this.pzbh;
		result = result * 37 + this.lx.hashCode();
		result = result * 37 + this.mc.hashCode();
		
		return result;
	}

	public int getBh()
	{
		return this.bh;
	}

	public void setBh(int bh)
	{
		this.bh = bh;
	}

	public int getPzbh()
	{
		return this.pzbh;
	}

	public void setPzbh(int pzbh)
	{
		this.pzbh = pzbh;
	}

	public String getLx()
	{
		return this.lx;
	}

	public void setLx(String lx)
	{
		this.lx = lx;
	}

	public String getMc()
	{
		return this.mc;
	}

	public void setMc(String mc)
	{
		this.mc = mc;
	}

//	public Set<TJfkfxm> getKfxms() {
//		return kfxms;
//	}
//
//	public void setKfxms(Set<TJfkfxm> kfxms) {
//		this.kfxms = kfxms;
//	}

}
